namespace: stefan0xC
name: zimbra
version: 0.0.1
authors:
- Stefan Melmuk <stefan.melmuk@gmail.com>

readme: README.md
description: Ansible Collection to manage a Zimbra Installation (e.g. user management, distribution lists, ACLs, etc.) 
# license: GPL-2.0
license_file: 'LICENSE'
tags: []

dependencies: {}

repository: https://github.com/stefan0xC/zimbra-collection
documentation: https://github.com/stefan0xC/zimbra-collection/wiki
homepage:  https://github.com/stefan0xC/zimbra-collection
issues: https://github.com/stefan0xC/zimbra-collection/issues
build_ignore: []
